<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CallScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends AppRepository
{
    public function getGroupByUser($userId) {
        $query = $this->createQueryBuilder("g")
            ->select('g')
            ->Join("g.userGroup", "ug")
            ->where("ug.user = :userId")
            ->setParameter("userId",$userId);
        return $query->getQuery()->getResult();
    }

    public function checkAdminGroup($userId, $groupId) {
        $query = $this->createQueryBuilder("g")
            ->select('g')
            ->Join("g.userGroup", "ug")
            ->where("ug.user = :userId")
            ->andWhere("ug.group = :groupId")
//            ->andWhere("ug.role = :role")
            ->setParameter("userId",$userId)
            ->setParameter("groupId",$groupId);
//            ->setParameter("role", 1);
        return $query->getQuery()->getResult();
    }
}
